---
driver:
  name: vagrant
  provider: docker

lifecycle:
  pre_converge:
    # install net-tools which are required (but missing in the docker baseimage) for testing listen ports etc
    - remote: sudo apt-get install net-tools -y

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.12.3
  chef_omnibus_install_options: -d /tmp/vagrant-cache/

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04-dockerized
    driver:
      box: tknerr/baseimage-ubuntu-18.04
  - name: ubuntu-16.04-dockerized
    driver:
      box: tknerr/baseimage-ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[myapp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: