---
driver:
  name: vagrant
  provider: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.12.3
  chef_omnibus_install_options: -d /tmp/vagrant-cache/

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04-dockerized
    driver:
      box: tknerr/baseimage-ubuntu-18.04
    lifecycle:
      pre_converge:
        - remote: sudo apt-get install net-tools -y
  - name: ubuntu-16.04-dockerized
    driver:
      box: tknerr/baseimage-ubuntu-16.04
    lifecycle:
      pre_converge:
        - remote: sudo apt-get install net-tools -y

suites:
  - name: default
    run_list:
      - recipe[myapp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: