---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.12.3
  chef_omnibus_install_options: -d /tmp/vagrant-cache/

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      provider: docker
      box: tknerr/baseimage-ubuntu-18.04
    lifecycle:
      pre_converge:
        - remote: sudo wget -O /bin/systemctl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py

suites:
  - name: default
    run_list:
      - recipe[myapp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: